# Generated by Django 2.2.10 on 2021-09-13 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitBackAndEarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('car_year', models.CharField(max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_owner/cars/')),
                ('particulars', models.ImageField(blank=True, null=True, upload_to='car_owner/particulars/')),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='car_owner/id_cards/')),
                ('status', models.CharField(default='pending', max_length=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_licence', models.BooleanField(default=False)),
                ('licence_issue_date', models.DateField()),
                ('licence_exp_date', models.DateField()),
                ('licence_no', models.CharField(max_length=20)),
                ('comments', models.TextField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwnerDriverRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=10)),
                ('nationality', models.CharField(choices=[('nigeria', 'Nigeria')], default='Nigeria', max_length=20)),
                ('state_of_origin', models.CharField(choices=[('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('akwa-ibom', 'Akwa-Ibom'), ('delta', 'Delta'), ('edo', 'Edo'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('ondo', 'Ondo'), ('imo', 'Imo'), ('bauchi', 'Bauchi'), ('plateau', 'Plateau'), ('ogun', 'Ogun'), ('kaduna', 'Kaduna'), ('katsina', 'Katsina'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('benue', 'Benue'), ('kogi', 'Kogi'), ('fct(Abuja)', 'FCT(Abuja)'), ('ebonyi', 'Ebonyi'), ('cross-rivers', 'Cross-Rivers')], max_length=15)),
                ('lga_of_origin', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=100)),
                ('state_of_residence', models.CharField(choices=[('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('akwa-ibom', 'Akwa-Ibom'), ('delta', 'Delta'), ('edo', 'Edo'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('ondo', 'Ondo'), ('imo', 'Imo'), ('bauchi', 'Bauchi'), ('plateau', 'Plateau'), ('ogun', 'Ogun'), ('kaduna', 'Kaduna'), ('katsina', 'Katsina'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('benue', 'Benue'), ('kogi', 'Kogi'), ('fct(Abuja)', 'FCT(Abuja)'), ('ebonyi', 'Ebonyi'), ('cross-rivers', 'Cross-Rivers')], default='fct(Abuja)', max_length=50)),
                ('lga_of_residence', models.CharField(max_length=50)),
                ('address_of_residence', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_relationship', models.CharField(choices=[('spouse', 'Spouse'), ('brother', 'Brother'), ('sister', 'Sister'), ('father', 'Father'), ('mother', 'Mother'), ('cousin', 'Cousin'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('neighbour', 'Neighbour'), ('son', 'Son'), ('daughter', 'Daughter'), ('son', 'Son')], max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('1', 'Current'), ('2', 'Savings')], max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
