# Generated by Django 2.2.10 on 2021-09-13 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0002_remove_carownerdriverregister_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitBackAndEarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.BooleanField(default=False)),
                ('car_brand', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_owner/cars/')),
                ('particulars', models.ImageField(blank=True, null=True, upload_to='car_owner/particulars/')),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='car_owner/id_cards/')),
                ('status', models.CharField(default='pending', max_length=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
