# Generated by Django 2.2.10 on 2021-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_sitbackandearn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitbackandearn',
            name='car_brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitbackandearn',
            name='car_make',
            field=models.CharField(max_length=100),
        ),
    ]
