# Generated by Django 2.2.10 on 2021-09-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20210913_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitbackandearn',
            old_name='car_brand',
            new_name='model',
        ),
    ]
