# Generated by Django 2.2.10 on 2021-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20210913_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitbackandearn',
            name='car_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
