# Generated by Django 2.2.10 on 2021-09-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_auto_20210913_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitbackandearn',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
