# Generated by Django 2.2.10 on 2021-09-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20210913_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitbackandearn',
            name='car_year',
        ),
    ]
