# Generated by Django 2.2.10 on 2021-09-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_driverrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='status',
            field=models.CharField(default='pending', max_length=9),
        ),
    ]
