# Generated by Django 2.2.10 on 2021-09-03 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_driverrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
