# Generated by Django 2.2.10 on 2021-09-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210903_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverrequest',
            name='interview',
        ),
    ]
