# Generated by Django 2.2.10 on 2021-09-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210907_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carownerdriverregister',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankAccountInformation',
        ),
        migrations.DeleteModel(
            name='CarOwnerDriverRegister',
        ),
        migrations.DeleteModel(
            name='DriverRequest',
        ),
    ]
