# Generated by Django 2.2.10 on 2021-09-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='service_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.RideServiceClass'),
            preserve_default=False,
        ),
    ]
