# Generated by Django 2.2.10 on 2021-09-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_auto_20210907_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='service_type',
        ),
    ]
