# Generated by Django 2.2.10 on 2021-09-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_remove_ride_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
