# Generated by Django 2.2.10 on 2021-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_auto_20210907_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
