# Generated by Django 2.2.10 on 2021-09-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0010_servicetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='comments',
            field=models.TextField(default='Ok', max_length=500),
            preserve_default=False,
        ),
    ]
