# Generated by Django 2.2.10 on 2021-09-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0012_auto_20210910_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
